build:
  version: "1.3"

accounts:
  message: "Welcome to Eazybank accounts related Production APIs"
  contactDetails:
    name: "Miller Watson - Developer"
    email: "mwatson@eazybank.com"
  onCallSupport:
    - (555)555-1234
    - (555)523-1345