build:
  version: "1.1"

cards:
  message: "Welcome to Eazybank cards related local APIs"
  contactDetails:
    name: "Dexter smith"
    email: "dexter@eazybank.com"
  onCallSupport:
    - (555)424-5642
    - (555)426-879