build:
  version: "2.1"

cards:
  message: "Welcome to Eazybank cards related QA APIs"
  contactDetails:
    name: "Jack Daniel"
    email: "jack@eazybank.com"
  onCallSupport:
    - (555)424-5142
    - (555)426-8719