build:
  version: "3.1"

cards:
  message: "Welcome to Eazybank cards related Production APIs"
  contactDetails:
    name: "Lakshmi Nivas"
    email: "lakshmi@eazybank.com"
  onCallSupport:
    - (555)456-8697
    - (555)421-8962
