build:
  version: "4.1"

loans:
  message: "Welcome to Eazybank loans related Production APIs"
  contactDetails:
    name: "kannan"
    email: "kannan@eazybank.com"
  onCallSupport:
    - (555)421-6598
    - (555)414-6678