build:
  version: "3.8"

loans:
  message: "Welcome to Eazybank loans related QA APIs"
  contactDetails:
    name: "Anand krishna"
    email: "anand@eazybank.com"
  onCallSupport:
    - (555)423-6999
    - (555)494-6078